### ISSUE TITLE
schema url 404

### ISSUE THREAD

**Issue by jb33k** [charlestati/schema-org-json-schema#18]
It looks like `https://schema.org/version/latest/schema.jsonld` isn't a valid URL anymore and Schema.org has changed their release naming and how files are organized.

**Comment by charlestati** [comment]
Hi @jb33k! Thank you for letting me know. According to [this page](https://schema.org/docs/developers.html) we could use this URL instead:

https://schema.org/version/latest/schemaorg-current-https.jsonld

Unfortunately, I won't have time to update the repository for a while.
